spring :
  datasource :
    url : ${DATABASE_URL}
    username : ${DATABASE_USERNAME}
    password : ${DATABASE_PASSWORD}

  jpa :
    show-sql : true
    hibernate :
      ddl-auto : update

oauth2 :
  facebook :
    access-token-url : https://graph.facebook.com/v9.0/oauth/access_token
    user-info-url : https://graph.facebook.com/me
    client-id : ${FACEBOOK_CLIENT_ID}
    client-secret : ${FACEBOOK_CLIENT_SECRET}

jwt :
  secret : ${JWT_SECRET}

payments :
  stripe-secret-key: sk_test_51II8FYARlvoNFDxNWEQ6BiODLI6SXC6Bn1HEfLJ99uBnjezkpiXpryaENDIITJEQ7AtY8E66ZoTSl8HmZ5eBcBHl00dDsEjNPJ
  specialists-payouts-cron: 0 0 0 ? * * *
